# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Quenya spellchecker"
qya = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Quenya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
qya = "TRANSLATE: A spellchecker for Quenya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.qya"

[windows]
system_product_code = "{EDA3AE19-D45F-49EB-B4D6-99C611094D51}_is1"

[package.speller]
name = "Quenya"
version = "0.1.0"

[package.grammar]
name = "Quenya"
version = "0.1.0"

[package.tts-text-proc]
name = "Quenya"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
