template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "quen1234"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-qya"
__UND2C__ = "qya"
__UNDEFINED__ = "Quenya"
__UND__ = "qya"
