template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "quen1234"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-qya"
__UND2C__ = "qya"
__UNDEFINED__ = "Quenya"
__UND__ = "qya"
