template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "quen1234"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-qya"
__UND2C__ = "qya"
__UNDEFINED__ = "Quenya"
__UND__ = "qya"
